name : first-ci-cd 

on : 
 push : 
  branches : [ main ] 
jobs : 
 test-python :
  strategy : 
   matrix : 
    os : [ubuntu-latest , windows-latest ] 
  runs-on : ${{ matrix.os }} 
  - use : "actions/checkout@v4" 
  - name : Set up Python env.
    use : "actions/setup-python@v5
    with : 
     python-version : '3.11' 
  - name : install-requirements 
    run : |
     python -m pip install --upgrade pip 
     python -m pip install -r requirements.txt
     python new.py 
  - name : eventul-msg 
    run : echo "bro the task has finished " 
